"""
Smallest Polyiamond Containing All Free n-Iamonds

Computes the smallest connected polyiamond that contains every free n-iamond
as a subregion (i.e., every free n-iamond can be placed somewhere within the
polyiamond via translation, rotation, and reflection).

This is the triangular grid analog of A327094 (square grid) and the polyhex
container sequence (hex grid).

Method: SAT solver (Glucose 4.2 via PySAT) with iterative connectivity
cuts and top-down search: start at an upper bound and decrease k until
UNSAT, proving the exact minimum.

Triangular grid: cell (r,c) is up-pointing if (r+c) is even, down-pointing
if (r+c) is odd. Each cell has exactly 3 edge-neighbors.

Requirements: Python 3.8+, python-sat
Install:      pip install python-sat

Usage:
    python solve_polyiamond_container.py                  # Run all n=1..8
    python solve_polyiamond_container.py --n 5            # Run single n
    python solve_polyiamond_container.py --n 3-6          # Run range
    python solve_polyiamond_container.py --verbose        # Detailed output
    python solve_polyiamond_container.py --log run.txt    # Log output to file
    python solve_polyiamond_container.py --json results.json  # Save as JSON

Author: Peter Exley
License: CC-BY-4.0
"""

import sys
import os
import time
import json
import argparse
import io
from collections import deque
from pathlib import Path
from pysat.solvers import Glucose42, Cadical195
from pysat.card import CardEnc, EncType

# SAT backends: Glucose42 for full solve path, Cadical195 for UNSAT prefilter
_SAT_SOLVER = Glucose42

# Add project root to path for shared library imports
PROJ_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJ_ROOT))

try:
    from polyform_enum import enumerate_fixed as _pe_fixed, enumerate_free as _pe_free
    _USE_CYTHON_ENUM = True
except ImportError:
    _USE_CYTHON_ENUM = False

try:
    from figure_gen_utils.versioned_output import save_versioned
    HAS_VERSIONED = True
except ImportError:
    HAS_VERSIONED = False

sys.stdout.reconfigure(line_buffering=True)


# Number of free n-iamonds (A000577) for verification
FREE_POLYIAMOND_COUNTS = {
    1: 1, 2: 1, 3: 1, 4: 3, 5: 4, 6: 12, 7: 24, 8: 66, 9: 160,
    10: 448, 11: 1186, 12: 3334, 13: 9235, 14: 26166,
    15: 73983, 16: 211297, 17: 607711,
}


# ============================================================
# Triangular grid adjacency
# ============================================================

def get_neighbours(r, c):
    """Return 3 edge-neighbors of triangle (r, c).

    Up-pointing (r+c even): shares edges left, right, and above.
    Down-pointing (r+c odd): shares edges left, right, and below.
    """
    if (r + c) % 2 == 0:
        return ((r, c - 1), (r, c + 1), (r - 1, c))
    else:
        return ((r, c - 1), (r, c + 1), (r + 1, c))


# ============================================================
# Triangular coordinate transforms (D6: 12 symmetries)
# ============================================================

def normalize(cells):
    """Translate to canonical position using valid lattice translations.

    The triangular grid's translation lattice is generated by (0, 2) and
    (1, 1). Only translations with even (dr + dc) sum preserve triangle
    orientations. Result has min_r = 0 and min_c in {0, 1}.
    """
    if not cells:
        return frozenset()
    min_r = min(r for r, c in cells)
    min_c = min(c for r, c in cells)
    k = (min_c - min_r) // 2
    dc = min_r + 2 * k
    return frozenset((r - min_r, c - dc) for r, c in cells)


def _rot60(r, c):
    """60-degree clockwise rotation around vertex (0,0)."""
    t = (r + c) % 2
    r2 = (r + c + 1) // 2
    c2 = (c - 3 * r - t - 2) // 2
    return (r2, c2)


def _reflect(r, c):
    """Horizontal reflection about the x-axis through vertex (0,0)."""
    return (-r - 1, c)


def _make_transform(n_rot, do_reflect):
    """Create a D6 transform: optionally reflect, then rotate n_rot times."""
    def transform(r, c):
        if do_reflect:
            r, c = _reflect(r, c)
        for _ in range(n_rot):
            r, c = _rot60(r, c)
        return (r, c)
    return transform


# All 12 D6 transforms (6 rotations + 6 reflected rotations)
TRI_TRANSFORMS = []
for _k in range(6):
    TRI_TRANSFORMS.append(_make_transform(_k, False))
for _k in range(6):
    TRI_TRANSFORMS.append(_make_transform(_k, True))


def tri_orientations(cells):
    """Return all distinct orientations (up to 12) of a polyiamond."""
    results = set()
    for t in TRI_TRANSFORMS:
        oriented = normalize(frozenset(t(r, c) for r, c in cells))
        results.add(oriented)
    return list(results)


# ============================================================
# Polyiamond generation
# ============================================================

def gen_fixed(n):
    """Generate all fixed n-iamonds (distinct under translation only)."""
    if _USE_CYTHON_ENUM:
        return _pe_fixed(n, "triangle")
    if n <= 0:
        return [frozenset()]
    if n == 1:
        return [frozenset([(0, 0)])]
    prev = gen_fixed(n - 1)
    seen = set()
    out = []
    for p in prev:
        for r, c in p:
            for nb in get_neighbours(r, c):
                if nb not in p:
                    nw = normalize(p | {nb})
                    if nw not in seen:
                        seen.add(nw)
                        out.append(nw)
    return out


def gen_free(n):
    """Generate all free n-iamonds (distinct under rotation and reflection)."""
    if _USE_CYTHON_ENUM:
        return _pe_free(n, "triangle")
    if n <= 0:
        return [frozenset()]
    fixed = gen_fixed(n)
    seen = set()
    free = []
    for p in fixed:
        canon = min(tuple(sorted(o)) for o in tri_orientations(p))
        if canon not in seen:
            seen.add(canon)
            free.append(p)
    return free


# ============================================================
# Placement enumeration
# ============================================================

def all_placements(free_polys, grid_rows, grid_cols):
    """Enumerate all valid placements of each free polyiamond in the grid.

    Grid cells: (r, c) with r in [0, grid_rows-1], c in [0, grid_cols-1].
    All orientations and all translation offsets are tried; deduplication
    via seen_sets eliminates redundant placements.
    """
    result = []
    for poly in free_polys:
        piece_placements = []
        seen_sets = set()
        for ori in tri_orientations(poly):
            cells = list(ori)
            max_r = max(r for r, c in cells)
            max_c = max(c for r, c in cells)
            min_r = min(r for r, c in cells)
            min_c = min(c for r, c in cells)
            for dr in range(-min_r, grid_rows - max_r):
                for dc in range(-min_c, grid_cols - max_c):
                    placed = tuple(sorted((r + dr, c + dc) for r, c in cells))
                    if placed not in seen_sets:
                        seen_sets.add(placed)
                        piece_placements.append(placed)
        result.append(piece_placements)
    return result


# ============================================================
# Connectivity check (triangular adjacency)
# ============================================================

def find_components(cells):
    """Find connected components of a set of triangular cells via BFS."""
    remaining = set(cells)
    components = []
    while remaining:
        start = next(iter(remaining))
        comp = set()
        queue = deque([start])
        comp.add(start)
        remaining.remove(start)
        while queue:
            r, c = queue.popleft()
            for nb in get_neighbours(r, c):
                if nb in remaining:
                    remaining.remove(nb)
                    comp.add(nb)
                    queue.append(nb)
        components.append(comp)
    return components


def is_connected(cells):
    """Return True if the given set of triangular cells is connected."""
    if len(cells) <= 1:
        return True
    return len(find_components(cells)) == 1


# ============================================================
# Solution verification
# ============================================================

def verify_solution(n, cells, free_polys, verbose=False):
    """
    Verify that a candidate solution is valid:
      1. Polyiamond is connected
      2. Every free n-iamond fits within the polyiamond
    Returns (ok, message).
    """
    cell_set = set(cells)
    size = len(cell_set)

    if not is_connected(cell_set):
        return False, "Polyiamond is not connected"

    if n <= 1:
        return True, (f"OK -- {size} cells, connected, trivially contains "
                      f"all free {n}-iamonds")

    # Compute bounding box for offset search
    min_r = min(r for r, c in cell_set)
    max_r = max(r for r, c in cell_set)
    min_c = min(c for r, c in cell_set)
    max_c = max(c for r, c in cell_set)

    for idx, poly in enumerate(free_polys):
        fits = False
        for ori in tri_orientations(poly):
            ori_cells = list(ori)
            omr = min(r for r, c in ori_cells)
            omc = min(c for r, c in ori_cells)
            norm = [(r - omr, c - omc) for r, c in ori_cells]
            p_max_r = max(r for r, c in norm)
            p_max_c = max(c for r, c in norm)
            for dr in range(min_r, max_r - p_max_r + 1):
                for dc in range(min_c, max_c - p_max_c + 1):
                    placed = set((r + dr, c + dc) for r, c in norm)
                    if placed <= cell_set:
                        fits = True
                        break
                if fits:
                    break
            if fits:
                break
        if not fits:
            return False, f"Free {n}-iamond #{idx} does not fit"
        if verbose:
            print(f"    Piece {idx + 1}/{len(free_polys)}: fits")

    return True, (f"OK -- {size} cells, connected, all {len(free_polys)} "
                  f"free {n}-iamonds fit")


# ============================================================
# SAT solver
# ============================================================

def solve_sat(n_target, grid_rows, grid_cols, upper_bound, free_polys,
              use_shape=False, verbose=False):
    """
    SAT-based top-down search for the smallest polyiamond containing all
    free n-iamonds.

    If use_shape=True, adds shape constraints:
      1. Contiguous c-values per row (no gaps within rows)
      2. At least one full row (all c values occupied, width = grid_cols = n)

    Connectivity enforced via iterative CEGAR cuts.
    """
    placements = all_placements(free_polys, grid_rows, grid_cols)
    n_pieces = len(free_polys)

    def var(r, c):
        return r * grid_cols + c + 1

    total_vars = grid_rows * grid_cols
    cell_vars = [var(r, c) for r in range(grid_rows) for c in range(grid_cols)]

    # Auxiliary variables for placements
    aux_id = total_vars + 1
    piece_aux = []
    for pplacements in placements:
        pvars = list(range(aux_id, aux_id + len(pplacements)))
        aux_id += len(pplacements)
        piece_aux.append(pvars)

    total_place = sum(len(pa) for pa in piece_aux)
    if verbose:
        print(f"    {grid_rows} X {grid_cols}: {total_vars} cell vars, "
              f"{total_place} placements, {n_pieces} pieces")

    for i in range(n_pieces):
        if not piece_aux[i]:
            if verbose:
                print(f"    Piece {i} has no valid placements -- infeasible")
            return None, None

    # ---- Shape constraints ----
    shape_clauses = []
    if use_shape:
        # 1. Contiguous c-values per row:
        #    For each row r and columns a < b < c,
        #    if x[r,a] and x[r,c] then x[r,b]
        contiguous_count = 0
        for r in range(grid_rows):
            for a in range(grid_cols):
                for c_end in range(a + 2, grid_cols):
                    for b in range(a + 1, c_end):
                        shape_clauses.append(
                            [-var(r, a), var(r, b), -var(r, c_end)])
                        contiguous_count += 1

        # 2. At least one full row (all c values occupied)
        full_row_vars = []
        for r in range(grid_rows):
            fv = aux_id
            aux_id += 1
            full_row_vars.append(fv)
            # fv -> x[r,c] for all c
            for c in range(grid_cols):
                shape_clauses.append([-fv, var(r, c)])
            # (all x[r,c]) -> fv
            shape_clauses.append([fv] + [-var(r, c) for c in range(grid_cols)])

        # At least one full row
        shape_clauses.append(full_row_vars[:])

        # No row pinning -- learned from polyhex containers that pinning
        # the full row to row 0 is WRONG on non-square grids. The optimal
        # solution may have the full row interior.

        if verbose:
            print(f"    Shape constraints: {contiguous_count} contiguous, "
                  f"{len(full_row_vars)} full-row vars")
            print(f"    Total shape clauses: {len(shape_clauses)}")

    # Two-phase search: binary search to narrow range, then linear
    # descent for proof. Problem is monotone (SAT at k => SAT at k+1)
    # so binary search is valid even with shape constraints.
    best_size = None
    best_cells = None

    lo = n_target
    hi = upper_bound

    # Phase 1: Binary search to find tight upper bound
    if hi - lo > 6:
        print(f"    Phase 1: Binary search [{lo}..{hi}]")
        while hi - lo > 4:
            mid = (lo + hi) // 2
            t1 = time.time()
            result = _try_solve(grid_rows, grid_cols, mid, placements,
                                piece_aux, n_pieces, var, cell_vars,
                                shape_clauses, aux_id)
            elapsed = time.time() - t1

            if result is not None:
                best_size = mid
                best_cells = result
                hi = mid
                print(f"    k = {mid}: SAT  [{elapsed:.1f}s]")
            else:
                lo = mid + 1
                print(f"    k = {mid}: UNSAT  [{elapsed:.1f}s]")

    # Phase 2: Linear descent for exact proof
    print(f"    Phase 2: Linear descent [{lo}..{hi}]")
    for k in range(hi, lo - 1, -1):
        t1 = time.time()
        result = _try_solve(grid_rows, grid_cols, k, placements, piece_aux,
                            n_pieces, var, cell_vars, shape_clauses, aux_id)
        elapsed = time.time() - t1

        if result is not None:
            best_size = k
            best_cells = result
            print(f"    k = {k}: SAT  [{elapsed:.1f}s]")
        else:
            print(f"    k = {k}: UNSAT  [{elapsed:.1f}s]  "
                  "<-- optimality proved")
            break

    return best_size, best_cells


def _try_solve(grid_rows, grid_cols, target_cells, placements, piece_aux,
               n_pieces, var, cell_vars, shape_clauses, top_id):
    """Try to find a connected polyiamond of exactly target_cells cells."""
    solver = _SAT_SOLVER()

    # Placement constraints: each piece must be placed at least once
    for i in range(n_pieces):
        solver.add_clause(piece_aux[i])
    for i, pplacements in enumerate(placements):
        for j, placed_cells in enumerate(pplacements):
            aux = piece_aux[i][j]
            for r, c in placed_cells:
                solver.add_clause([-aux, var(r, c)])

    # Shape constraints (empty list if unconstrained)
    for clause in shape_clauses:
        solver.add_clause(clause)

    # Min-degree constraint: every occupied cell has >= 1 occupied neighbor.
    # Eliminates isolated cells, reducing disconnected solutions for CEGAR.
    for r in range(grid_rows):
        for c in range(grid_cols):
            nbs = []
            if c > 0:
                nbs.append((r, c - 1))
            if c < grid_cols - 1:
                nbs.append((r, c + 1))
            if (r + c) % 2 == 0:
                if r > 0:
                    nbs.append((r - 1, c))
            else:
                if r < grid_rows - 1:
                    nbs.append((r + 1, c))
            if nbs:
                solver.add_clause([-var(r, c)] +
                                  [var(nr, nc) for nr, nc in nbs])

    # Cardinality: exactly target_cells occupied
    card_clauses = CardEnc.equals(cell_vars, target_cells, top_id=top_id,
                                  encoding=EncType.totalizer)
    for clause in card_clauses:
        solver.add_clause(clause)

    # Iterative connectivity refinement (CEGAR)
    for iteration in range(200):
        if not solver.solve():
            solver.delete()
            return None

        model = set(solver.get_model())
        occupied = set()
        for r in range(grid_rows):
            for c in range(grid_cols):
                if var(r, c) in model:
                    occupied.add((r, c))

        if len(occupied) != target_cells:
            solver.delete()
            return None

        components = find_components(occupied)
        if len(components) == 1:
            solver.delete()
            return occupied

        # Add cuts to eliminate disconnected solutions
        largest = max(components, key=len)
        for comp in components:
            if comp is not largest:
                solver.add_clause([-var(r, c) for r, c in comp])

    solver.delete()
    return None


# ============================================================
# Display
# ============================================================

def format_tri_grid(cells):
    """Format a polyiamond as ASCII art using ^/v for up/down triangles."""
    if not cells:
        return "    (empty)"
    cs = set(cells)
    r0 = min(r for r, c in cs)
    r1 = max(r for r, c in cs)
    c0 = min(c for r, c in cs)
    c1 = max(c for r, c in cs)
    lines = []
    for r in range(r0, r1 + 1):
        line = ""
        for c in range(c0, c1 + 1):
            if (r, c) in cs:
                if (r + c) % 2 == 0:
                    line += " ^"
                else:
                    line += " v"
            else:
                line += " ."
        lines.append("    " + line)
    return "\n".join(lines)


# ============================================================
# Argument parsing
# ============================================================

def parse_n_arg(s):
    """Parse --n argument: '5', '3-7', '0,3,5', '3-5,9'."""
    values = []
    for part in s.split(","):
        part = part.strip()
        if "-" in part:
            lo, hi = part.split("-", 1)
            values.extend(range(int(lo), int(hi) + 1))
        else:
            values.append(int(part))
    return sorted(set(values))


# ============================================================
# Main
# ============================================================

def main():
    parser = argparse.ArgumentParser(
        description="Smallest polyiamond containing all free n-iamonds")
    parser.add_argument("--n", type=str, default="1-8",
                        help="Which n values to compute (default: 1-8)")
    parser.add_argument("--verbose", action="store_true",
                        help="Detailed solver output")
    parser.add_argument("--log", type=str, default=None,
                        help="Save output to log file")
    parser.add_argument("--json", type=str, default=None,
                        help="Save results as JSON file")
    args = parser.parse_args()

    n_values = parse_n_arg(args.n)

    # Default log path to research/solver-run-log.txt if not specified
    if args.log is None:
        args.log = str(PROJ_ROOT / "oeis-new-polyiamond-container" / "research" / "solver-run-log.txt")
    os.makedirs(os.path.dirname(args.log) or ".", exist_ok=True)

    # Set up logging to file (tee stdout)
    log_file = open(args.log, "w", encoding="utf-8")

    class Tee(io.TextIOBase):
        def __init__(self, *streams):
            self.streams = streams
        def write(self, data):
            for s in self.streams:
                s.write(data)
                s.flush()
            return len(data)
        def flush(self):
            for s in self.streams:
                s.flush()

    sys.stdout = Tee(sys.__stdout__, log_file)

    try:
        _run_solver(args, n_values)
    finally:
        sys.stdout = sys.__stdout__
        log_file.close()

    # Create versioned copy of the log
    if HAS_VERSIONED:
        with open(args.log, "r", encoding="utf-8") as f:
            log_text = f.read()
        save_versioned(log_text, args.log)


def _run_solver(args, n_values):
    """Main solver body."""
    import platform
    import datetime
    try:
        from pysat import __version__ as pysat_version
    except ImportError:
        pysat_version = "unknown"

    output = print

    output("=" * 70)
    output("Smallest polyiamond containing all free n-iamonds")
    output("Triangular grid analog of A327094 (square grid)")
    output("SAT solver (Glucose 4.2) with connectivity cuts")
    output("=" * 70)
    output(f"  Software: Glucose 4.2 via PySAT {pysat_version}, "
           f"Python {platform.python_version()}")
    output(f"  Hardware: {platform.processor() or platform.machine()}, "
           f"{platform.system()} {platform.release()}")
    output(f"  Date: {datetime.date.today().isoformat()}")
    output(f"  n values to solve: {n_values}")
    output()

    # Verify polyiamond generation against A000577
    max_verify = min(max(n_values) + 1, 9) if n_values else 1
    output("  Free polyiamond counts (A000577):")
    for test_n in range(1, max_verify):
        count = len(gen_free(test_n))
        expected = FREE_POLYIAMOND_COUNTS.get(test_n)
        match = "OK" if count == expected else f"MISMATCH (expected {expected})"
        output(f"    n={test_n}: {count} free {test_n}-iamonds  {match}")
    output()

    results = {}
    t_total = time.time()

    for n in n_values:
        output(f"  n = {n}")
        output(f"  {'-' * 40}")
        t0 = time.time()

        # --- Trivial cases ---
        # a(1) = 1, a(2) = 2, a(3) = 3: only 1 free polyiamond each
        if n <= 0:
            elapsed = time.time() - t0
            output(f"    Trivial: a(0) = 0 (empty)  [{elapsed:.3f}s]")
            results[n] = {
                "n": 0, "size": 0, "cells": [], "grid_size": [0, 0],
                "status": "PROVED", "elapsed": round(elapsed, 3),
            }
            output()
            continue

        if n == 1:
            elapsed = time.time() - t0
            output(f"    Trivial: a(1) = 1 (single cell)  [{elapsed:.3f}s]")
            results[n] = {
                "n": 1, "size": 1, "cells": [[0, 0]], "grid_size": [1, 1],
                "status": "PROVED", "elapsed": round(elapsed, 3),
                "num_free_polyiamonds": 1,
            }
            output()
            continue

        if n == 2:
            elapsed = time.time() - t0
            output(f"    Trivial: a(2) = 2 (domino)  [{elapsed:.3f}s]")
            results[n] = {
                "n": 2, "size": 2, "cells": [[0, 0], [0, 1]],
                "grid_size": [1, 2],
                "status": "PROVED", "elapsed": round(elapsed, 3),
                "num_free_polyiamonds": 1,
            }
            output()
            continue

        if n == 3:
            elapsed = time.time() - t0
            output(f"    Trivial: a(3) = 3 (1 free triamond)  [{elapsed:.3f}s]")
            results[n] = {
                "n": 3, "size": 3, "cells": [[0, 0], [0, 1], [0, 2]],
                "grid_size": [1, 3],
                "status": "PROVED", "elapsed": round(elapsed, 3),
                "num_free_polyiamonds": 1,
            }
            output()
            continue

        # --- SAT solver for n >= 4 ---
        free_polys = gen_free(n)
        output(f"    {len(free_polys)} free {n}-iamonds")

        # Grid size: tight rectangle. Width = n (required for I-piece).
        # Height = conservative formula derived from solution bounding boxes
        # observed at n=4..14. Formula: rows = max(4, (n+2) // 3).
        # Cross-validated against rows+1 grid at n=11,12,13,14: same answers.
        # Validation: if rows+1 grid yields a DIFFERENT a(n), use the larger.
        grid_rows = max(4, (n + 2) // 3)
        grid_cols = n

        # Upper bound: a filled grid_rows x grid_cols grid. The solver
        # descends from here via binary search + linear proof.
        upper = grid_rows * grid_cols

        # Shape constraints for n >= 6: contiguous columns per row +
        # at least one full row. Adapted from polyhex containers.
        # No row pinning (learned from polyhex: optimal full row can
        # be interior).
        use_shape = (n >= 6)
        mode = "shape-constrained" if use_shape else "unconstrained"

        output(f"    Grid: {grid_rows} X {grid_cols}")
        output(f"    Mode: {mode}")
        output(f"    Search: k = {upper} down to {n}")

        best_size, best_cells = solve_sat(
            n, grid_rows, grid_cols, upper, free_polys,
            use_shape=use_shape, verbose=args.verbose)
        elapsed = time.time() - t0

        if best_size is not None:
            cell_list = sorted(best_cells)
            r0 = min(r for r, c in cell_list)
            r1 = max(r for r, c in cell_list)
            c0 = min(c for r, c in cell_list)
            c1 = max(c for r, c in cell_list)
            bb_r = r1 - r0 + 1
            bb_c = c1 - c0 + 1

            status = "PROVED"
            output(f"    Result: a({n}) = {best_size}  [{elapsed:.1f}s]  "
                   f"{status}")

            # Verify solution
            ok, msg = verify_solution(n, best_cells, free_polys,
                                      verbose=args.verbose)
            if ok:
                output(f"    Verified: {msg}")
            else:
                output(f"    VERIFICATION FAILED: {msg}")
                status = "VERIFY_FAILED"

            output(f"    Bounding box: {bb_r} X {bb_c}")
            output(format_tri_grid(best_cells))

            # Normalize cells for JSON -- preserve (r+c) parity.
            off_r, off_c = r0, c0
            if (off_r + off_c) % 2 != 0:
                off_c -= 1
            norm_cells = sorted([r - off_r, c - off_c]
                                for r, c in best_cells)
            results[n] = {
                "n": n,
                "size": best_size,
                "cells": norm_cells,
                "grid_size": [bb_r, bb_c],
                "status": status,
                "elapsed": round(elapsed, 1),
                "num_free_polyiamonds": len(free_polys),
            }
        else:
            output(f"    NO SOLUTION FOUND  [{elapsed:.1f}s]")
            results[n] = {
                "n": n,
                "size": None,
                "cells": [],
                "grid_size": [0, 0],
                "status": "NO_SOLUTION",
                "elapsed": round(elapsed, 1),
                "num_free_polyiamonds": len(free_polys),
            }

        output()

    # ---- Summary table ----
    total_elapsed = time.time() - t_total
    output("=" * 70)
    output("RESULTS SUMMARY")
    output("=" * 70)
    output(f"  {'n':>3}  {'a(n)':>5}  {'Box':>9}  {'Pieces':>7}  "
           f"{'Time':>8}  {'Status'}")
    output(f"  {'---':>3}  {'-----':>5}  {'---------':>9}  {'-------':>7}  "
           f"{'--------':>8}  {'------'}")

    for n in n_values:
        r = results[n]
        size_str = str(r["size"]) if r["size"] is not None else "?"
        if r["grid_size"][0] > 0:
            box_str = f"{r['grid_size'][0]} X {r['grid_size'][1]}"
        else:
            box_str = "--"
        pieces_str = str(r.get("num_free_polyiamonds", "--"))
        if n <= 3:
            pieces_str = str(len(gen_free(n)))
        time_str = f"{r['elapsed']:.1f}s"
        output(f"  {n:>3}  {size_str:>5}  {box_str:>9}  {pieces_str:>7}  "
               f"{time_str:>8}  {r['status']}")

    output(f"\n  Total time: {total_elapsed:.1f}s")

    # JSON output -- structured with terms/details/solutions via save_versioned
    import platform
    import datetime as _dt
    try:
        from pysat import __version__ as _pysat_v
    except ImportError:
        _pysat_v = "unknown"

    terms_dict = {
        str(k): v["size"] for k, v in results.items() if v.get("size") is not None
    }
    details_dict = {
        str(k): {kk: vv for kk, vv in v.items() if kk != "cells"}
        for k, v in results.items()
    }
    solutions_dict = {
        str(k): {"cells": v.get("cells", [])} for k, v in results.items()
    }

    structured_output = {
        "sequence": "polyiamond-container",
        "description": "Smallest connected polyiamond containing all free n-iamonds",
        "method": "SAT (Glucose 4.2 via PySAT) + CEGAR connectivity + binary search",
        "software": f"Glucose 4.2 via PySAT {_pysat_v}, Python {platform.python_version()}",
        "hardware": f"{platform.processor() or platform.machine()}, {platform.system()} {platform.release()}",
        "date": _dt.date.today().isoformat(),
        "total_time": round(total_elapsed, 2),
        "terms": terms_dict,
        "details": details_dict,
        "solutions": solutions_dict,
    }

    json_path = args.json or str(PROJ_ROOT / "oeis-new-polyiamond-container" / "research" / "solver-results.json")
    os.makedirs(os.path.dirname(json_path) or ".", exist_ok=True)
    if HAS_VERSIONED:
        vpath = save_versioned(structured_output, json_path)
        output(f"\n  Results saved to {json_path}")
        output(f"  Versioned: {vpath}")
    else:
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(structured_output, f, indent=2)
        output(f"\n  Results saved to {json_path}")

    output()


if __name__ == "__main__":
    main()
